### ISSUE TITLE
init scripts don't run on route transitions

### ISSUE THREAD

**Issue by jamiechong** [laantorchaweb/ember-cli-slick#11]
I'm trying to use dynamic slides dependent on the route. Ex: 

```
{{#slick-slider autoplay=false arrows=true}}
  {{#each model.slides as |slide|}}
  <div class="box"> <img src="{{slide}}"> </div>
  {{/each}}
{{/slick-slider}}            
```

I have routes like this: 
`/page/1`, `/page/2`, `/page/3`

The `model.slides` depends on the pageId

It works when I'm on a current page and refresh the page. But if I transition from `/page/1` to `/page/2`, the component doesn't rebuild itself with the new content. Similarly, if I transition from `/index` (no slides) to `/page/1`, the component seems to load fine, but the container height is only 1px.

**Comment by laantorchaweb** [comment]
Where do you have the code for the component? on the `pages.hbs` template? or is it on the `pages/page.hbs`?

**Comment by jamiechong** [comment]
In this example it would be on `pages.hbs`. I'll try to switch things around a bit to setup a `page.hbs` template if you think it'll help. Currently I'm trying to figure out how to call a slick method (`slickFilter`) on `didTransition` in hopes that it'll reInit the underlying jQuery plugin
