### ISSUE TITLE
Responsive breakpoints not working.

### ISSUE THREAD

**Issue by v3ss0n** [laantorchaweb/ember-cli-slick#15]
I tried as given in the example and set a controller property with breakpoints. But it is not working.

**Comment by laantorchaweb** [comment]
@v3ss0n you can see the example of the dummy app here:
`https://github.com/laantorchaweb/ember-cli-slick/blob/master/tests/dummy/app/controllers/application.js`

You can also download this repo and try `ember serve` to see the dummy app working. It shows different configuration using the responsive option.

**Comment by tommy-CP68** [comment]
Hi,
I followed very closely to your dummy app. However, I was unable to get the carousel working in the responsive mode. I am using ember 3.10.1.

**Comment by BrennanRoberts** [comment]
Are you sure this is actually fixed? The dummy app had the same problem for us and seems to disregard the intended config. The problem appears to be [this line](https://github.com/laantorchaweb/ember-cli-slick/blob/b1a1886799714de6de7183b50dd013800d187926/addon/components/slick-slider.js#L52) which overwrites the provided value.
