### ISSUE TITLE
ember-cli tests (ember test) hangs when using this addon

### ISSUE THREAD

**Issue by 4xposed** [laantorchaweb/ember-cli-slick#2]
I noticed that the tests hang and don't run after build whenever I use this addon.

It still happen son an new empty project:

```
ember new blabla
cd blabla
ember install ember-cli-slick
ember test
```

and after `Build project successfully...` hangs there indefinitely.

**Comment by 4xposed** [comment]
fixed it and made a PR https://github.com/laantorchaweb/ember-cli-slick/pull/3

**Comment by laantorchaweb** [comment]
Awesome, thank you!
