### ISSUE TITLE
Addon doesn't work with ember version 2.12 onwards.

### ISSUE THREAD

**Issue by SanthoshRaju91** [laantorchaweb/ember-cli-slick#23]
Hello @laantorchaweb ,

We have been using this addon in our project and during the upgrade, I found out that the addon was not compatible with the version 2.12.3, since ember have now moved to ember-source and ember-cli-shims for managing bower dependencies. 

Kindly review the PR and let me know if there is any changes I need to make so you may merge it. Always happy to help.

Warm Regards

**Comment by laantorchaweb** [comment]
The 3.0.0 release should work now.
