### ISSUE TITLE
Pull requests merging?

### ISSUE THREAD

**Issue by MrChriZ** [laantorchaweb/ember-cli-slick#31]
@laantorchaweb - Is there any chance getting some of the pull requests for this project getting merged?
Or is this project dead?

Cheers,
Chris.

**Comment by laantorchaweb** [comment]
It’s not dead, I’m sorry. I’ll work on merging this and pushing a new version this weekend.

**Comment by laantorchaweb** [comment]
Well, it took some months and I'm sorry. I had to take care of something that took me away of this. Let me know if you found any issues with the latest release (it's a major change)
