### ISSUE TITLE
Getting error (The package `ember-cli-slick` is not a properly formatted package}

### ISSUE THREAD

**Issue by dagoodlife** [laantorchaweb/ember-cli-slick#4]
The package `ember-cli-slick` is not a properly formatted package, we have used a fallback lookup to resolve it at `C:\Users\Carlos\Desktop\web-apps\del_sur\node_modules\ember-cli-slick`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
The `ember-cli-slick` addon could not be found at `C:\Users\Carlos\Desktop\web-apps\del_sur\node_modules\ember-cli-slick`.

**Comment by dagoodlife** [comment]
Trying to use this slider but keep getting this error on install, any idea what could be happening?

**Comment by laantorchaweb** [comment]
I saw that warning but the slider is working ok on my end, the default main entry point points to index.js, so it shouldn't be needed. Can you confirm that the slider isn't working and post your ember-cli version please?

**Comment by dagoodlife** [comment]
Yea it is not working on my end for some reason here is ember version I am using

 DEBUG: -------------------------------
ember.debug.js:4888 DEBUG: Ember      : 1.12.0
ember.debug.js:4888 DEBUG: Ember Data : 1.0.0-beta.18
ember.debug.js:4888 DEBUG: jQuery     : 1.11.3
ember.debug.js:4888 DEBUG: -------------------------------

**Comment by dagoodlife** [comment]
Let me re-install it see if changes anything

**Comment by laantorchaweb** [comment]
ok, I see that it may be related to this npm issue: https://github.com/npm/npm/issues/5082 I'll add the main entry point and publish it again.

**Comment by dagoodlife** [comment]
Awesome thank you, I will update you once I test it out on my end to confirm its working fine. Appriciate the fast feedback.

**Comment by laantorchaweb** [comment]
I published a new version to NPM with the specified entry point. I've created a new ember app and then `ember install ember-cli-slick` it didn't threw any errors now:

```
➜  testApp git:(master) ember install ember-cli-slick
version: 1.13.5
Installed packages for tooling via npm.
installing ember-cli-slick
Installing browser packages via Bower...
  cached git://github.com/kenwheeler/slick.git#1.5.8
Installed browser packages via Bower.
Installed addon package.
```

If you can confirm I'll appreciate it.

**Comment by dagoodlife** [comment]
Working Fine, thanks again.
