### ISSUE TITLE
custom pagination

### ISSUE THREAD

**Issue by maoamid** [laantorchaweb/ember-cli-slick#9]
Hi,
How can I customize the dots, to became something like ids, or tabs name?
Or how can I use the slick methods like: slickGoTo, slickCurrentSlide, slickNext, slickPrev to realize that?
I appreciate any hint.

**Comment by TobiasLounsbury** [comment]
@maoamid I needed to do something similar recently so I added a bound property called currentSlide that allow the controller to manipulate navigation between slides. I've initiated a PR against the master branch, or if you still need this functionality and the PR hasn't yet been merge and haven't found another work-around you can check out the master branch of my Fork.
